### ISSUE TITLE
Automatic upload of tracks and shows to archive.org

### ISSUE THREAD

**Issue by JonTheNiceGuy** [CCHits/Website#87] opened 2018-09-11 12:29 UTC
_From @JonTheNiceGuy on October 28, 2015 8:10_

This reduces the dependency on Dreamhost (for their unlimited storage)

_Copied from original issue: CCHits/cchits-next-wishlist#2_

**Comment by thelovebug** [comment] 2018-09-11 12:31
Duplicate of #66

**Closed by thelovebug** 2018-09-11 12:31 UTC
Labels: Back End
